Remove fluidbox arrows from ducts
raiguard/FluidMustFlow pull request #11
Opened 2023-02-26 14:09 UTC by heinwessels

Removes the fluidbox arrows that was changed to be added-by-default in Factorio 1.1.67. Now it looks like it shows on the mod portal :)

From this:
![image](https://user-images.githubusercontent.com/39875036/221415564-98aea7a1-ab78-4ac6-b9dd-d16325ce4ce0.png)

To this:
![image](https://user-images.githubusercontent.com/39875036/221415603-9361fee2-1de4-4547-a6dd-c7e21e1de300.png)

2023-02-26 20:05 UTC, raiguard requested changes
Overall, looks good! Thanks for the contribution. Just one minor thing:

2023-02-26 20:05 UTC, raiguard commented on changelog.txt
> +    - Remove blue fluidbox arrows from ducts (#11)
I usually prefer to use past-tense in my changelogs ("Removed" instead of "Remove").

2023-02-27 06:57 UTC, heinwessels commented on changelog.txt
> +    - Remove blue fluidbox arrows from ducts (#11)
Done

2023-02-27 07:40 UTC, raiguard approved these changes

2023-02-27 07:41 UTC, merged